---
  - name: General | Load varibles
    include_vars:
      file: vars.yml
        
  - name: K8S | Install Minion | Join K8S with kubeadm
    shell: kubeadm join --token={{ kubeadm_token }} --discovery-token-unsafe-skip-ca-verification {{ k8s_master_ip }}:6443 --node-name={{ k8s_node_ip }}
    become: true
    become_method: sudo