---
- name: Configure jenkins machines with java
  hosts: jenkins_machines
  roles:
    - jenkins_common

- name: Install Jenkins Server Nadav Way
  hosts: jenkins_masters
  roles:
    - jenkins_server

- name: Clean Jenkins
  hosts: jenkins_masters2
  roles:
    - jenkins_server_old

- name: Configure node machine with docker
  hosts: jenkins_nodes
  roles:
    - kubernetes_docker