#!/bin/bash

## installing ansible server ##
sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
sudo yum update -y
sudo yum install ansible -y
sudo yum install git -y

## installing pip3 and passlib library with pip
sudo yum install python34-setuptools -y
sudo easy_install-3.4 pip -y
sudo pip3 install passlib

echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2vi5IkpI3uPTnNkH+lwbdrHOnnYMAoiZ8+woJvwskNFV58GZkcI0ZrB5CKid/O4dYQSmM9xinRoO+untxoUL+v5nHV2Mvtc1VTamWERiCnxb35P9E+CuBhIae9Hul2O8PH+EUAwmJcHHShQ+qpRXftMe9GIqvrJKhi5WEct6pMbv/5d/+dOjujVLiz2R0qxlNwzV3mWpmMZLXcq3bZTKbzO1E/sXz74og5MYgFDJkhwxnRtmgcY6uzkCecAeOm8qfkyfqLfyO77mR/8gKh7+o9//KzSH9rhY8vPcYzn5zuM4KEGvgwfDTr03nw5p6gcVrQEJeMbAGU94aKH5Y28Ej ec2-user@ip-172-31-45-203.eu-central-1.compute.internal" >> /home/ec2-user/.ssh/authorized_keys

sudo echo "-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAtr4uSJKSN7j05zZB/pcG3axzp52DAKImfPsKCb8LJDRVefBm
ZHCNGaweQionfzuHWEEpjPcYp0aDvrp7caFC/r+Zx1djL7XNVU2plhEYgp8W9+T/
RPgrgYSGnvR7pdjvDx/hFAMJiXBx0oUPqqUV37THvRiKr6ySoYuVhHLeqTG7/+Xf
/nTo7o1S4s9kdKsZTcM1d5lqZjGS13Kt22Uym8ztRP7F8++KIOTGIBQyZIcMZ0bZ
oHGOrs5AnnAHjpvKn5Mn6i38ju+5kf/ICoe/qPf/ys0h/a4WPLz3GM5+c7jOChBr
4MHw069N58OaeoHFa0BCXjGwBlPeGih+WNvBIwIDAQABAoIBAHoK2O4utOfx5dzk
J37XbgZtPXAbiXnK0Nl27mVD6TTsnokpO7ioUhNrF2oorOgT4XfXTOCPxS8xsJqY
AAkLIarwWsr+WYdraw4lJ7TJBg12Iei8Tp7I/oUo9J8Dt/AyyLTZHYA35w6awelO
ZAAa8FjOavamhTh9kA/DIL+r13g2VOX5tn8/uKwnRmXvOj/Mi16Bxt4iRbMaBVxS
DpNQzBt9hk3wQV3+TzR/m7vaAo0bWyv6yAXE9LZE7i+b5Wb6MpmPy6YTpLkM8vXF
p2UH0EN37Fp4oN06i3lKxdfnAjoOQloTEF9DlZVlyHvfOlq+n23L9qGtwsNi23HB
sIfS8cECgYEA6y7vVoRDM5Wrio4MRtvdXpHqNmmR9jY2e55e8rVVEX6Phmtocm/5
nSMRdqWeOE8ze7lHn74Wce3dM7piWNxwMWqwCEkRqEBmhlSD1hnkI2PrayaYfs+O
cog6zfnNLHXw4+3hJZDfa4prvF1pv5wgzHEoN4swXNuzGNoDVnKtTT8CgYEAxur8
0+sFQZuDqyYryeQxYNQCVEONfbOb3a2jyYd87K6RGjscS9oPZabwdevZ+yopQ23/
S9ljtSMOIQgeN6/JR2RSCY5N6aPUC09+3N4pK88VwMCgSWYFMqH9Lqx58CSFoYiS
CePFkyGEh0iEHmDUZWpUGPgh6byuKPANvxNovx0CgYA9HeJWomJwWlnM1OM92s8p
T1QFNeQXjrkT4PEds5/avv//V5Q6AP1mJ4HXSmzWh0aCxYBmc9iTXNQaKDp8izSg
su/yB0MObUX3bKkiD3Jo/ANmwg3pDnkfLGXTtzHpdvDV2rCiuYZGBR/AQKpFgAZJ
+rIP1R0JVJKzR5yMb5q3swKBgQDCe8YuPD6rYq1djLiLcDyG+0I7uMCCAjWGi9rz
kzClCBh+mQSVdOJQ9ONtp+c8FoC5mLZfJnDCDUAnM5S3xXr5/i/nf+bVZIRReqwC
roN6fcI67xrIKKM0WgT8uU2PaWXuBWUjnjryG3dD/baPLQT9EvSeZRxjN0Lga7RE
+WkUUQKBgQDbjbfAZosjmhMRDsEAsP5FY169hZ0tYwXmt+UyVqKjDGuCO4yhrM92
g8KaG7sfxhMybQw5N9a4JWvqScWRJRmFnl8E51eTSqVK7dlybFaSWw8URJDCk2ti
TGWH+fm5UNhQoslsMLTAUxJ3Q064WnS3QZ5eA6bOQLMB3gcZqaCL5Q==
-----END RSA PRIVATE KEY-----" > /home/ec2-user/.ssh/id_rsa

# to make the ssh key usable in rhel permissions should be limited
chmod 0600 /home/ec2-user/.ssh/id_rsa