#!/bin/bash

###Setting some in scripts vars for later easier edit

# foundations path
REPO_HOME_FOLDER='/home/ubuntu/finalProject-OpsSchool'
TERRAFORM_VARIABLE_FILE=$REPO_HOME_FOLDER/'terraform/vars'
TERRAFORM_VARIABLE_TEMP_FILE=$REPO_HOME_FOLDER/'terraform/tempVars'

# user data path
ANSIBLE_PATH=$REPO_HOME_FOLDER/'ansible'

### setting a "tempVars" file to replace the original "vars" file
cat $TERRAFORM_VARIABLE_FILE | head -3 > $TERRAFORM_VARIABLE_TEMP_FILE

### adding the data to the "tempVars" file

# Ansible
echo 'ansible_server_user_data_script = "'$ANSIBLE_PATH/RHEL/initial_call_for_server'"' >> $TERRAFORM_VARIABLE_TEMP_FILE
echo 'ubuntu_ansible_server_user_data_script = "'$ANSIBLE_PATH/ubuntu/initial_call_for_server'"' >> $TERRAFORM_VARIABLE_TEMP_FILE




### moving the new data from "tempVars" to "vars"
cat $TERRAFORM_VARIABLE_TEMP_FILE > $TERRAFORM_VARIABLE_FILE
rm -rf $TERRAFORM_VARIABLE_TEMP_FILE



