---
- name: General | Load varibles
  include_vars:
    file: vars.yml
      
- name: Nadav Role | ensure jenkins is running
  service:
    name: jenkins
    state: started
  become: true
  become_method: sudo

- name: Wait for Jenkins to start
  uri:
    url: "{{ jenkins_url }}:{{ jenkins_port }}"
  become: false
  register: jenkins_home_content
  # Jenkins will return 503 (service unavailable) on the home page while
  # starting (the "Please wait while Jenkins is getting ready to work" page)
  until: jenkins_home_content.status == 200
  retries: 30
  delay: 5

- name: Install plugin
  jenkins_plugin:
    name: "{{ item }}"
  with_items: "{{ jenkins_plugins }}"
  notify:
  - restart jenkins