#!/bin/bash

## install and activate prometheus
wget https://github.com/prometheus/prometheus/releases/download/v2.6.0/prometheus-2.6.0.linux-amd64.tar.gz
tar xvfz prometheus-*.tar.gz
cd prometheus-2.6.0.linux-amd64
echo "  - job_name: dummy_consul_job
    consul_sd_configs:
      - server: 'localhost:8500'
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,dummy,.*
        action: keep
      - source_labels: [__meta_consul_service]
        target_label: DUMMY_RELABEL" >> ./prometheus.yml
./prometheus --config.file=prometheus.yml &