#!/bin/bash

###Setting some in scripts vars for later easier edit

USER_HOME_FOLDER='/home/ubuntu'
REPO_HOME_FOLDER=$USER_HOME_FOLDER'/finalProject-OpsSchool'
ANSIBLE_PATH=$REPO_HOME_FOLDER/'ansible/ubuntu'
ANSIBLE_PLAYBOOK_PATH=$ANSIBLE_PATH/../'playbooks'
CONSUL_PATH=$REPO_HOME_FOLDER/'consul/ubuntu'
KUBERNETES_PATH=$REPO_HOME_FOLDER/'kubernetes'
SPREE_PATH=$REPO_HOME_FOLDER/'spree'

## cloning git repo
cd $USER_HOME_FOLDER
git clone https://github.com/L1nuxProdigy/finalProject-OpsSchool
git clone https://github.com/L1nuxProdigy/spree

## installing consul
$CONSUL_PATH/'consul_client_spree'

## adding public key so jenkins master can connect
$ANSIBLE_PATH/'ansible_node'

## Spree Stuff

# installing docker might need some tweaking

# installing Docker CE Prerequisites
sudo apt-get update -y
sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# to validate the fingerprint use the following command
# sudo apt-key fingerprint 0EBFCD88

# Installing Docker CE
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get install docker-ce -y


## in practive does nothing, for validation only
chown -R ubuntu $REPO_HOME_FOLDER
touch initial_call_finished.checkpoint
