---
- hosts: jenkins_master_hosts
  vars_files:
    - ./variables.yml
  remote_user: ubuntu
  become: yes
  tasks:
  - name: install openjdk
    apt:
      name: openjdk-8-jre-headless
      update_cache: yes