---
kubeadm_token: "gqv3y0.91c3dhvt24c2s63h"
k8s_master_ip: kubernetes_master_enter_here
k8s_node_ip: kubernetes_node_one_enter_here
replication_controller_deployment_path: /home/ubuntu/finalProject-OpsSchool/kubernetes/replication_controller.yml
svc_deployment_path: /home/ubuntu/finalProject-OpsSchool/kubernetes/service.yml
kube_path_ubuntu_user: /home/ubuntu/.kube

jenkins_fixed_config_files_path: /home/ubuntu/finalProject-OpsSchool/jenkins/config_files/JenkinsRunningFolder
jenkins_home_folder: /var/lib/jenkins

jenkins_config_xml_debian: "{{ jenkins_home_folder }}/config.xml"

jenkins_config_xml_fixed: "{{ jenkins_fixed_config_files_path }}/config.xml"
jenkins_location_xml: "{{ jenkins_fixed_config_files_path }}/jenkins.model.JenkinsLocationConfiguration.xml"
jenkins_credentials_xml: "{{ jenkins_fixed_config_files_path }}/credentials.xml"
jenkins_users_dir: "{{ jenkins_fixed_config_files_path }}/users"

jenkins_java_opts: "-Djenkins.install.runSetupWizard=false"