#!/bin/bash

LOCAL_IPV4=$(curl "http://169.254.169.254/latest/meta-data/local-ipv4")

## kibana prerequisites- JAVA
sudo add-apt-repository ppa:openjdk-r/ppa -y
sudo apt-get update -y
sudo apt-get install openjdk-8-jdk-headless -y

## kibana install
wget https://artifacts.elastic.co/downloads/kibana/kibana-6.5.4-amd64.deb
dpkg -i kibana-6.5.4-amd64.deb

# setting an interactive shell variable named x3 as a local ip for a consul node
x=$(dig @127.0.0.1 -p 8600 consul-elasticsearch.node.consul +noall +answer | tail -n1)
x2=${x# }
x3=$(echo $x2 | cut -d ' ' -f5)

## finding the elastic_search private ip
while [[ ${#x3} = 0 ]]; do
        sleep 15
		x=$(dig @127.0.0.1 -p 8600 consul-elasticsearch.node.consul +noall +answer | tail -n1)
		x2=${x# }
		x3=$(echo $x2 | cut -d ' ' -f5)
done

## kibana configuration
echo 'elasticsearch.url: "http://'${x3}':9200"' >> /etc/kibana/kibana.yml
echo 'server.host: "'$LOCAL_IPV4'"' >> /etc/kibana/kibana.yml

systemctl enable kibana
systemctl start kibana

# checking if kibana is up- wonky way
lines_in_page=$(curl 'http://'${LOCAL_IPV4}':5601/app/kibana#/management/kibana/objects?_g=()' | wc -l)
while [[ $lines_in_page = 0 ]]; do
	sleep 15
	lines_in_page=$(curl 'http://'${LOCAL_IPV4}':5601/app/kibana#/management/kibana/objects?_g=()' | wc -l)
done
# creating filebeat index-patternt
/home/ubuntu/finalProject-OpsSchool/elk/json/kibana_script_for_all_curls


