---
apiVersion: v1
kind: Service
metadata:
  name: spree-test-service
  labels:
    app: spree-test
spec:
  type: NodePort
  ports:
  - port: 3000
    name: spreeport
    nodePort: 30001
    protocol: TCP
  selector:
    app: spree-test