---
apiVersion: v1
kind: Pod
metadata:
  name: spree-test
spec:
  containers:
  - name: spree-test
    image: spreecommerce/spree:3.6.4
    ports:
    - containerPort: 3000
  nodeSelector:
    Destiny: SpreeApp