---
apiVersion: v1
kind: ReplicationController
metadata:
  name: spree-test
spec:
  replicas: 1
  selector:
    app: spree-test
  template:
    metadata:
      labels:
        app: spree-test
    spec:
      containers:
      - name: spree-test
        image: d0ckerprodigy/spreeproject
        ports:
        - containerPort: 3000
      nodeSelector:
        Destiny: SpreeApp