#!/bin/bash

# installing docker might need some tweaking

# installing Docker CE Prerequisites
sudo apt-get update -y
sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# to validate the fingerprint use the following command
# sudo apt-key fingerprint 0EBFCD88

# Installing Docker CE
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get install docker-ce -y

# installing k8s

apt-get update && apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl


# more requirements

# 1. install docker - might need adjustment in the version

# 2. as long as running k8s without minimum requirements the command will be kubeadm init --ignore-preflight-errors all

# 3. run this as the user:
  # mkdir -p $HOME/.kube
  # sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  # sudo chown $(id -u):$(id -g) $HOME/.kube/config


# 3. adding the weave network plugin kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

# 4. need to check this kubeadm join 10.0.1.41:6443 --token he07rm.t7vhd0oljvjrkrr1 --discovery-token-ca-cert-hash sha256:5dd12f48855cf2763c0bd231ff14522cdf386e1996e12657bd23d2989d2f359d
	# kubeadm token list
	# openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | \openssl dgst -sha256 -hex | sed 's/^.* //'

# 5. some commands
	# kubectl get pods --all-namespaces
	# kubectl get nodes
	
