#!/bin/bash

###Setting some in scripts vars for later easier edit

USER_HOME_FOLDER='/home/ubuntu'
REPO_HOME_FOLDER=$USER_HOME_FOLDER'/finalProject-OpsSchool'
ANSIBLE_PATH=$REPO_HOME_FOLDER/'ansible/ubuntu'
ANSIBLE_PLAYBOOK_PATH=$ANSIBLE_PATH/../'playbooks'
CONSUL_PATH=$REPO_HOME_FOLDER/'consul/ubuntu'

## cloning git repo
cd $USER_HOME_FOLDER
git clone https://github.com/L1nuxProdigy/finalProject-OpsSchool

## installing consul
$CONSUL_PATH/'consul_server'

## installing ansible server
$ANSIBLE_PATH/'ansible_server'

### Pushing the Ansible Configurations from server to clients
$ANSIBLE_PATH/'followed_called_script_1'


## in practive does nothing, for validation only
chown -R ubuntu $REPO_HOME_FOLDER
touch initial_call_finished.checkpoint
