#!/bin/bash

###Setting some in scripts vars for later easier edit

USER_HOME_FOLDER='/home/ec2-user'
REPO_HOME_FOLDER=$USER_HOME_FOLDER'/finalProject-OpsSchool'
ANSIBLE_PATH=$REPO_HOME_FOLDER/'ansible'

## cloning git repo
cd $USER_HOME_FOLDER
git clone https://github.com/L1nuxProdigy/finalProject-OpsSchool

## installing consul
$ANSIBLE_PATH/'consul_server'

## installing ansible server
$ANSIBLE_PATH/'ansible_server'
